- name: "Initialize the environment"
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars_files:
    - "./vars/bootstrap_vars.yml"
    - "../vars/main.yml"
    - "~/agof_vault.yml"
  tasks:
    - name: "Assert that we have a valid target platform"
      ansible.builtin.assert:
        that:
          - (agof_bootstrap_target | default('aws')) | length > 0
          - (agof_bootstrap_target | default('aws')) in bootstrap_allowable_values
        fail_msg: "{{ agof_bootstrap_target | default('aws') }} is not a supported bootstrap target"
        success_msg: "Assertion passed: bootstrapping on {{ agof_bootstrap_target | default('aws') }}"

    - name: "Set our target bootstrap platform"
      ansible.builtin.set_fact:
        bootstrap_target: "{{ agof_bootstrap_target | default('aws') }}"

- name: "Initialize the environment on aws"
  ansible.builtin.import_playbook: "./aws/main.yml"
  tags:
    - tags_aws_init_env
  when: (agof_bootstrap_target | default('aws')) == 'aws'
