---
collections:
- infra.aap_configuration
- infra.aap_utilities
- ansible.posix
- ansible.utils
- amazon.aws
- community.aws
- community.general
- containers.podman
- redhat.rhel_system_roles
- ansible.netcommon
