---
teardown: false

ec2_wait: true
ec2_provision_instances: true
ebs_optimized_capable: false

ec2_instances:
  - name: aap
    # region_id:
    # security_group_id:
    # vpc_subnet_id:
    # image_id:       # optional; defaults to rhel_ami_id from lookup or rhel_ami_id_vault
    # bootstrap: true # optional; set false to skip RHSM registration and aap user prep
    # username:       # optional; defaults to ec2-user
    host_aliases:
      - aap
      - tower
    ansible_extra_groups:
      - aap_controllers
    instance_type: "{{ agof_aap_instance_type | default('m5.2xlarge') }}"
